
reference:
  annotation: reference/Homo_sapiens.GRCh38.116.chr.gtf
  hisat2_index: reference/hisat2_index/genome_tran

quantification:
  strandedness: 2

species:
  - 'Homo sapiens'

geneSet:
  - 'H'

gseaStat:
  - 'stat'

plot:
  # title of volcano plot
  volcano: 'Human bronchial epithielial cells: Normal VS Cystic Fibrosis'
  # title of barplot for GSEA
  barplot: 'Top Enriched Hallmark Pathways'
  
 
threads:
  align: 2
  samtools: 2
